---
title: "Infect matching overview"
author: "Zena Lapp"
date: "2023-06-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r}
library(tidyverse)
library(ggpubr)
library(DiagrammeR)
library(rsvg)
library(DiagrammeRsvg)
library(grImport2)

# set plotting theme
theme_set(theme_bw() + 
            theme(text = element_text(size = 15),
                  strip.background = element_rect(fill = 'white', color = 'white')))

reared <- read_csv('analysis/clean_data/data/reared.csv')
pairs <- read_csv('analysis/clean_data/data/reared_moz_hu_pairs.csv')
```

## Numbers

```{r}
survived_cts <- reared |> 
  group_by(surv_to_6) |> 
  tally() |> 
  ungroup() |> 
  mutate(tot = sum(n),
         prop = n/tot)

pos_cts <- reared |> 
  filter(surv_to_6 == 'Yes' & !is.na(pf_pcr_infection_status)) |> 
  group_by(pf_pcr_infection_status) |> 
  tally() |> 
  ungroup() |> 
  mutate(tot = sum(n),
         prop = n/tot)

n_moz_reared <- survived_cts |> filter(surv_to_6 == 'Yes') |> pull(tot)
n_moz_survived_to_6 <- survived_cts |> filter(surv_to_6 == 'Yes') |> pull(n)

(n_moz_tested <- pos_cts |> filter(pf_pcr_infection_status == 'positive') |> pull(tot))
(n_moz_pos <- pos_cts |> filter(pf_pcr_infection_status == 'positive') |> pull(n))
n_moz_pos/n_moz_tested

(n_moz_sequenced <- pairs |> 
  select(sample_id_mosquito) |> 
  n_distinct())
n_moz_sequenced/n_moz_pos

unique_hu <- pairs |> 
  filter(pair_type == 'same household') |> 
  select(M_ID, dbs_barcode, hu_pf_pcr_infection_status, n_reads_hu) |> 
  distinct()

n_hu_dbs <- nrow(unique_hu)
n_hu_tested <- unique_hu |> 
  filter(!is.na(hu_pf_pcr_infection_status)) |> 
  nrow()

(n_hu_pos <- unique_hu |> 
  filter(hu_pf_pcr_infection_status == 'positive') |> 
  nrow())
(n_hu_seq <- unique_hu |> 
  filter(hu_pf_pcr_infection_status == 'positive') |> 
  filter(!is.na(n_reads_hu)) |> 
  nrow())
n_hu_seq/n_hu_pos

(n_moz_with_match <- pairs |> 
  filter(pair_type == 'same household' & match == 'Yes') |> 
  select(sample_id_mosquito, match) |> 
  distinct() |> 
  nrow())
n_moz_with_match/n_moz_sequenced

n_hu_with_match <- pairs |> 
  filter(pair_type == 'same household' & match == 'Yes') |> 
  select(dbs_barcode, match) |> 
  distinct() |> 
  nrow()
```

## Figure

```{r}
hist_breaks <- c(18459, 18473, 18487, 18501, 18515, 18529, 18543, 18557, 18571, 
18585, 18599, 18613, 18627, 18641, 18655, 18669, 18683, 18697, 
18711, 18725, 18739, 18753, 18767, 18781, 18795, 18809, 18823, 
18837, 18851, 18865, 18879, 18893, 18907, 18459, 18473, 18487, 
18501, 18515, 18529, 18543, 18557, 18571, 18585, 18599, 18613, 
18627, 18641, 18655, 18669, 18683, 18697, 18711, 18725, 18739, 
18753, 18767, 18781, 18795, 18809, 18823, 18837, 18851, 18865, 
18879, 18893, 18907, 18459, 18473, 18487, 18501, 18515, 18529, 
18543, 18557, 18571, 18585, 18599, 18613, 18627, 18641, 18655, 
18669, 18683, 18697, 18711, 18725, 18739, 18753, 18767, 18781, 
18795, 18809, 18823, 18837, 18851, 18865, 18879, 18893, 18907, 
18459, 18473, 18487, 18501, 18515, 18529, 18543, 18557, 18571, 
18585, 18599, 18613, 18627, 18641, 18655, 18669, 18683, 18697, 
18711, 18725, 18739, 18753, 18767, 18781, 18795, 18809, 18823, 
18837, 18851, 18865, 18879, 18893, 18907) #generated by making the graph and pulling out of the data layer. This is just to make white lines so it looks pretty

infect_samples <- reared |> 
  left_join(pairs |> 
  filter(pair_type == 'same household' & match == 'Yes') |> 
  select(sample_id_mosquito, match) |> 
  distinct()) |> 
  mutate(type = case_when(surv_to_6 == 'No' ~ 'Reared',
                          is.na(pf_pcr_infection_status) ~ 'Survived to day 6',
                          pf_pcr_infection_status != 'positive' ~ 'Successfully tested for Pf',
                          is.na(n_haps_moz) ~ 'Pf positive',
                          !is.na(n_haps_moz) & is.na(match) ~ 'Successfully sequenced',
                          match == 'Yes' ~ 'Matched to human'),
         type = factor(type, levels = c('Reared', 'Survived to day 6', 'Successfully tested for Pf', 'Pf positive', 'Successfully sequenced', 'Matched to human'))) |> 
  ungroup() |> 
  mutate(tot = case_when(surv_to_6 == 'No' ~ n(),
                         is.na(pf_pcr_infection_status) ~ n() - sum(type == 'Reared'),
                          pf_pcr_infection_status != 'positive' ~ n() - sum(type %in% c('Reared', 'Survived to day 6')),
                          is.na(n_haps_moz) ~ n() - sum(type %in% c('Reared', 'Survived to day 6', 'Successfully tested for Pf')),
                          !is.na(n_haps_moz) & is.na(match) ~ sum(type %in% c('Successfully sequenced', 'Matched to human')),
                         match == 'Yes' ~ sum(type == 'Matched to human'))) |> 
  group_by(type) |> 
  mutate(type_n = paste0(type, ' (n = ', tot, ')'),
         type = factor(type_n)) |> 
  ggplot(aes(x = collection_date, fill = type)) +
  geom_histogram(binwidth = 14, linewidth = 0.2) +
  scale_fill_manual(values = c('grey85', 'grey75', 'grey65', '#6497b1', '#005b96', '#011f4b')) +
  labs(x = 'Collection date', y = 'Number of reared\nmosquitoes', fill = '') +
  scale_x_date(date_breaks = "3 months", date_labels =  "%b %Y") +
  geom_vline(xintercept = hist_breaks, col = "white") +
  labs(x = 'Collection date', y = 'Number of reared\nfemale Anopheles', fill = NULL) +
  theme(legend.position = c(0.35,0.75), legend.background = element_rect(linetype = "solid", color = "grey"), legend.title = element_blank(), legend.margin = margin(-4,5,5,5))
```

```{r}
haps_species <- reared |> 
  filter(species %in% c('An. gambiae SS', 'An. funestus') & surv_to_6 == 'Yes' & 
           pf_pcr_infection_status == 'positive' & !is.na(haps_moz)) |> 
  select(species, haps_moz) |> 
  separate_longer_delim(haps_moz, delim = ';') |> 
  group_by(species, haps_moz) |> 
  tally() |> 
  pivot_wider(names_from = species, values_from = n, values_fill = 0) 

haps_species |> 
  mutate(shared = `An. funestus` > 0 & `An. gambiae SS` > 0) |> 
  group_by(shared) |> 
  tally() |> 
  ungroup() |> 
  mutate(tot = sum(n),
         prop = n/tot)
```


```{r}
haps_species_plot <- haps_species |> 
  ggplot(aes(x = `An. gambiae SS`, y = `An. funestus`)) +
  geom_jitter(alpha = 0.75, width = 0.1, height = 0.1) +
  coord_fixed() +
  labs(x = 'Number of times haplotype\nobserved in An. gambiae SS',
       y = 'Number of times haplotype\nobserved in An. funestus')
```


```{r}
reared_flowchart <- grViz(paste("digraph reared {

  # nodes
  node [shape = box,
  fontname = Helvetica]
  n_moz_reared[label='", n_moz_reared, "\nreared female Anopheles']
  n_moz_survived_to_6[label='", n_moz_survived_to_6, "\nsurvived to day 6 or later']
  n_moz_tested[label='", n_moz_tested, "\nsuccessfully tested for\nP. falciparum in abdomen']
  n_moz_pos[label='", n_moz_pos, "\npositive for P. falciparum']
  n_moz_sequenced[label='", n_moz_sequenced, "\nsuccessfully sequenced\nat Pf-csp locus']
  n_moz_with_match[label='", n_moz_with_match, "\nhaplotype matched to a person\non the same household-day']
  
  n_hu_dbs[label='", n_hu_dbs, "\nhuman DBS on\nreared positive household-day']
  n_hu_tested[label='", n_hu_tested, "\nsuccessfully tested for\nP. falciparum']
  n_hu_pos[label='", n_hu_pos, "\npositive for P. falciparum']
  n_hu_seq[label='", n_hu_seq, "\nsuccessfully sequenced\nat Pf-csp locus']
  n_hu_with_match[label='", n_hu_with_match, "\nhaplotype matched to a mosquito\non the same household-day']

  
  # edge statements
  edge [fontname = Helvetica]
  n_moz_reared -> n_moz_survived_to_6
  n_moz_survived_to_6 -> n_moz_tested
  n_moz_tested -> n_moz_pos
  n_moz_pos -> n_moz_sequenced
  n_moz_sequenced -> n_moz_with_match
  
  n_hu_dbs -> n_hu_tested
  n_hu_tested -> n_hu_pos
  n_hu_pos -> n_hu_seq
  n_hu_seq -> n_hu_with_match
  
    subgraph {
rank = same; 'n_moz_sequenced'; 'n_hu_seq'
}
                  
} 

"))

reared_flowchart %>%
  export_svg() %>% 
  charToRaw() %>%
  rsvg_svg("analysis/manuscript_figures/figures/infect_flowchart.svg")

raw <- readPicture("analysis/manuscript_figures/figures/infect_flowchart.svg")
reared_flowchart <- pictureGrob(raw)
```

```{r}
### Infected mozzies over time
infect_matches <- pairs %>% 
  mutate(species = ifelse(species == 'Not determined', 'An. gambiae SL', species)) |> 
  filter(day_processed >= 6 & pair_type == 'same household') %>% 
  select(sample_id_mosquito, hh_id, collection_date, day_processed, species, n_haps_moz, match) %>% 
  distinct() %>%
  group_by(hh_id, collection_date) %>% 
  mutate(grp = as.numeric(factor(sample_id_mosquito)),
         grp_size = n(),
         village = gsub('[0-9]', '', hh_id)) %>% 
  ggplot(aes(x = collection_date, y = hh_id, col = species, 
             shape = match,
             group = grp)) +
  facet_grid(village~., scales = 'free', space = 'free') +
  geom_point(position = position_dodge(width = 1), size = 2, alpha = 0.75) +
  scale_color_manual(values = c('aquamarine4', 'pink3', 'mediumpurple4', 'grey50')) +
  scale_shape_manual(values = c(1, 16)) +
  scale_x_date(date_breaks = "2 months", date_labels =  "%b %Y") +
  labs(x = 'Mosquito collection date', y = 'Household', col = 'Species', 
       size = 'Number of\nhaplotypes in\nmosquito', shape = 'Haplotype match\nto human') +
  theme(axis.text.y = element_blank())
```


```{r, fig.width=10, fig.height=8.5}
(infect_overview <- ggarrange(ggarrange(infect_samples, haps_species_plot, 
                    widths = c(1.5, 1), labels = 'AUTO'),
          ggarrange(reared_flowchart, infect_matches, 
                    # widths = c(1, 6, 1), 
                    labels = c('C', 'D'), nrow = 1), 
          ncol = 1))

ggsave(plot = infect_overview, 
       filename = 'analysis/manuscript_figures/figures/infect_overview.png', 
       width = 10, height = 8.5)
```

### Check how many haplotypes were unique to mosquitoes

```{r}
haps_moz <- pairs |> 
  select(haps_moz) |> 
  separate_rows(haps_moz) |> 
  pull(haps_moz) |> 
  unique()
haps_hu <- pairs |> 
  select(haps_hu) |> 
  separate_rows(haps_hu) |> 
  pull(haps_hu) |> 
  unique()

length(haps_moz)
table(haps_moz %in% haps_hu)
length(haps_hu)
table(haps_hu %in% haps_moz)
```


